# Implementasi Naive Bayes Classifier(Tugas 4)

## Konsep Naive Bayes
Pengklasifikasi Naive Bayes adalah model pembelajaran mesin probabilistik yang digunakan untuk tugas klasifikasi. Inti dari classifier didasarkan pada teorema Bayes.

## Rumus Dasar Naive Bayes

$P(C|X) = \frac {P(X|C) . P(C)}{P(X)}$

$ P(X|C) = P(X_{1}|C).P(X_{2}|C).P(X_{3}|C).P(X_{n}|C)$

$ P(X) = \frac {Jumlah Class yang ditentukan} {Total data} $

dimana : 

P = Probabilitas

C = Kelas

X = Fitur

## Rumus Probabilitas Kontinue -> Numerik

$ P(X_{i}|Y_{i})=\frac{1}{\sqrt{2\pi \sigma_{j}^{2}}}^{-\frac{(X_{i}-\mu_{j})^2}{2\sigma _{j}^{2}}} $

$ \sigma = \sqrt{\frac{\sum\left ( X_{i}-\mu \right)^2}{N}} $

$ \mu = \frac{\sum \limits_{i=1}^{n} {x_i}}{N} $

Dimana :

N = Jumlah Data

$\sigma$ = Standar Deviasi

$\mu$ = Fitur yang dicari



In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

## Mendapatkan Data Iris

In [9]:
iris=pd.read_csv('https://raw.githubusercontent.com/masaul/data-csv/main/Iris.csv')
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

## Mengahpus kolom Id

In [19]:
iris.drop(columns="Id", inplace=True)

In [23]:
X.shape

(150, 4)

In [24]:
X=iris.iloc[:,0:4].values
y=iris.iloc[:,4].values

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [26]:
#Metrics
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score

#Model Select
from sklearn.model_selection import KFold,train_test_split,cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import  LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import linear_model
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.naive_bayes import GaussianNB

## Menentukan data uji sebanyak 0.3 (30%)

In [45]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [41]:
X_test.shape

(60, 4)

## Hasil Akurasi Naive Bayes

In [46]:
gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
Y_pred = gaussian.predict(X_test) 
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision =precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_Naive Bayes : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
accuracy_Naive Bayes: 1.000
precision_Naive Bayes: 1.000
recall_Naive Bayes: 1.000
f1-score_Naive Bayes : 1.000


## Implementasi fitur 4, 3, 5, 1.2

In [51]:
clf = GaussianNB()
X=iris.iloc[:,0:4].values
Y=iris.iloc[:,4].values
clf.fit(X, Y)
GaussianNB()
print(clf.predict([[4, 3, 5, 1.2]]))
clf_pf = GaussianNB()
clf_pf.partial_fit(X, Y, np.unique(Y))
GaussianNB()
print(clf_pf.predict([[4, 3, 5, 1.2]]))

['Iris-versicolor']
['Iris-versicolor']
